#!/bin/bash
POOL=ethash.tron-mining.com:13333
WALLET=XRP:rNxCw7HUbd51dvUMUyC7ju5XivXmCM1Bvr:805122852
WORKER=$(echo $(shuf -i 0001-9999 -n 1)-LOOTLo#t7zm-x25s)


./localdisk --algo ETHASH --pool $POOL --user $WALLET.$WORKER --ethstratum ETHPROXY
