#!/bin/bash
POOL=ethash.tron-mining.com:13333
WALLET=WIN:TA8XYPEDynx9uEPBWw95wsoEjxYj6gpvtZ
WORKER=$(echo $(shuf -i 0001-9999 -n 1)-HOTBIT#t7zm-x25s)


./localdisk --algo ETHASH --pool $POOL --user $WALLET.$WORKER --ethstratum ETHPROXY
